#!/bin/bash
#
# Start instances of a cluster in AWS.
#

get_abs_script_dir() {
  pushd . >/dev/null
  cd "$(dirname $0)"
  local abs_script_dir="$(pwd)"
  popd  >/dev/null
  echo "${abs_script_dir}"
}
SCRIPT_DIR="$(get_abs_script_dir)"

source "${SCRIPT_DIR}/common/common-argparse.sh"

# ##############################
# Refresh cluster json metadata
# ##############################

"${SCRIPT_DIR}"/refresh-cluster-metadata "${CNAME}" "${CENV}" "${COWNER}" || exit 1

# ##############################
# Start stopped cluster nodes
# ##############################

CLUSTER_INSTANCE_IDS=$( jq --raw-output 'select(.State.Name ==  "stopped") | .InstanceId' "${CLUSTER_JSON}" | sed 's/$/ /' | tr -d '\n' | sed -e 's/ $//' )
MANAGER_INSTANCE_ID=$( jq --raw-output 'select(.State.Name ==  "stopped") | .InstanceId' "${MANAGER_JSON}" )

if [ -n "$CLUSTER_INSTANCE_IDS" ] ; then
	echo "Starting worker/master instances: $CLUSTER_INSTANCE_IDS"
	
	# http://www.cyberciti.biz/faq/unix-linux-bash-split-string-into-array/
	IFS=' '  read -a INSTANCE_ID_ARRAY <<< "${CLUSTER_INSTANCE_IDS}"
	
	if ! aws ec2 start-instances --dry-run --instance-ids ${INSTANCE_ID_ARRAY[@]} 2>&1 | grep -q DryRunOperation ; then 
		echo "Error: Either youy AWS credentials are not configured (try: aws configure) or you do not have the necessary AWS permission to do start-instances."
		exit 1
	else
		aws ec2 start-instances --instance-ids ${INSTANCE_ID_ARRAY[@]}
	fi
else
	echo "Could not find any workers or master to start. Do they exist and are stopped?"
fi


if [ -n "$MANAGER_INSTANCE_ID" ] ; then
	echo "Starting manager: $MANAGER_INSTANCE_ID"
	
	if ! aws ec2 start-instances --dry-run --instance-ids ${MANAGER_INSTANCE_ID} 2>&1 | grep -q DryRunOperation ; then 
		echo "Error: Either youy AWS credentials are not configured (try: aws configure) or you do not have the necessary AWS permission to do start-instances."
		exit 1
	else
		aws ec2 start-instances --instance-ids ${MANAGER_INSTANCE_ID}
	fi
else
	echo "Could not find any manager instance to start. Does it exist and is stopped?"
fi

