bin.includes = META-INF/,\
               plugin.xml,\
               lib/,\
               LICENSE.txt,\
               CHANGELOG.md,\
               knime-databricks-driver.jar
src.includes = LICENSE.txt
bin.excludes = lib/fetch_jars275/
jars.compile.order = knime-databricks-driver.jar
source.knime-databricks-driver.jar = src/
output.knime-databricks-driver.jar = bin/
