#!/bin/bash
#
# Refresh public ip lists for a cluster.
#

get_abs_script_dir() {
  pushd . >/dev/null
  cd "$(dirname $0)"
  local abs_script_dir="$(pwd)"
  popd  >/dev/null
  echo "${abs_script_dir}"
}
SCRIPT_DIR="$(get_abs_script_dir)"

source "${SCRIPT_DIR}/common/common-argparse.sh"

# ##############################
# Refresh cluster json metadata
# ##############################

"${SCRIPT_DIR}"/refresh-cluster-metadata "${CNAME}" "${CENV}" "${COWNER}" || exit 1

# ##############################
# Create hostlists for use with pssh and other
# ##############################

jq --raw-output ".PublicIpAddress" "${ENV_JSON}" >"${ENV_HOSTS}"
jq --raw-output ".PublicIpAddress" "${CLUSTER_JSON}" >"${CLUSTER_HOSTS}"
jq --raw-output ".PublicIpAddress" "${WORKER_JSON}" >"${WORKER_HOSTS}"
jq --raw-output ".PublicIpAddress" "${MASTER_JSON}" >"${MASTER_HOSTS}"
jq --raw-output ".PublicIpAddress" "${MANAGER_JSON}" >"${MANAGER_HOSTS}"
echo "Refreshed public IP lists"
