bin.includes = META-INF/,\
               plugin.xml,\
               lib/,\
               LICENSE.txt,\
               CHANGELOG.md,\
               knime-databricks-driver-deprecated.jar
src.includes = LICENSE.txt
bin.excludes = lib/fetch_jars/,\
               lib/fetch_jars273/
jars.compile.order = knime-databricks-driver-deprecated.jar
source.knime-databricks-driver-deprecated.jar = src/
output.knime-databricks-driver-deprecated.jar = bin/
