#!/bin/bash


if [ "$#" -gt "0" ] ; then
        echo "This script prints the contents of a feature.xml to stdout, which contains all bundles"
        echo "generated by pom.xml."
        exit 0
fi

FEATURE_XML_HEADER='<?xml version="1.0" encoding="UTF-8"?>
<feature
      id="com.knime.features.bigdata.externals"
      label="Feature with all external plug-ins for the KNIME Big Data Extension"
      version="2.2.0.qualifier"
      provider-name="KNIME AG, Zurich, Switzerland">

      <!-- THIS FILE IS GENERATED BY generate_feature_xml.sh. MANUAL EDITS MAY THUS BE OVERWRITTEN -->
      '

FEATURE_XML_FOOTER="</feature>"

PLUGIN_TEMPLATE='   <plugin
         id=\"${plugin_name}\"
         download-size=\"0\"
         install-size=\"0\"
         version=\"${plugin_version}\"
         unpack=\"false\"/>
'

test -d ./target/repository || { echo >&2 "Could not find target/repository subfolder. Aborting."; exit 1; }


echo "${FEATURE_XML_HEADER}"
for fullfile in  ./target/repository/plugins/*.jar ; do
  jarfile=$(basename "${fullfile}")
  plugin_name=$(echo "$jarfile" | sed 's/^\(.*\)_[0-9]\+\.[0-9]\+\.[0-9]\+.*\.jar$/\1/' )
  plugin_version=$( echo "$jarfile" | sed 's/^.*_\([0-9]\+\.[0-9]\+\.[0-9]\+.*\)\.jar$/\1/' )
  eval "echo \"${PLUGIN_TEMPLATE}\""
done
echo "${FEATURE_XML_FOOTER}"

echo "#####################################################################################################################################" >&2
echo "# NOTE: If you are adding any fragments to the feature, you need to manually fix the feature.xml with fragment=\"true\" attributes! #" >&2
echo "#####################################################################################################################################" >&2
