- name: Fix JSDIR in spark-job-server-init.d
  replace:
    name: /opt/{{js_linkname}}/spark-job-server-init.d
    regexp: '^JSDIR=.+$'
    replace: 'JSDIR=/opt/{{js_linkname}}'

- name: Fix LOGDIR in spark-job-server-init.d
  replace:
    name: /opt/{{js_linkname}}/spark-job-server-init.d
    regexp: '^LOGDIR=.+$'
    replace: 'LOGDIR=/var/log/{{js_linkname}}'

- name: Reload systemctl services (if necessary)
  shell: command -v systemctl && systemctl daemon-reload

- name: Fix LOG_DIR in settings.sh
  replace:
    name: /opt/{{js_linkname}}/settings.sh
    regexp: '^LOG_DIR=.+$'
    replace: 'LOG_DIR=/var/log/{{js_linkname}}'
