- name: Configure jobserver for Kerberos (environment.conf)
  blockinfile:
    name: /opt/{{js_linkname}}/environment.conf
    block: |
      shiro {
          authentication = on
          config.path = "shiro.ini"
          use-as-proxy-user = on
      }

- name: Configure jobserver for Kerberos (shiro.ini)
  copy: src={{js_shiro_ini}} dest=/opt/{{js_linkname}}/shiro.ini owner=spark-job-server

- name: Configure jobserver for Kerberos (settings.sh)
  lineinfile:
    name: /opt/{{js_linkname}}/settings.sh
    line: export JOBSERVER_KEYTAB=/opt/{{js_linkname}}/jobserver.keytab

- name: Copy jobserver keytab
  copy: src={{keytab_dir}}/{{js_keytab}} dest=/opt/{{js_linkname}}/jobserver.keytab owner=spark-job-server mode=u=rw,go=
