---
- name: Create users
  user:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    uid: '{{ item.uid | default(omit) }}'
    group: '{{ item.group | default(item.name) }}'
    groups: '{{ item.groups | default("") | join(",") }}'
    shell: '{{ item.shell | default(users_default_shell) }}'
    comment: '{{ item.comment | default("Unknown User") }}'
    password: '{{ item.password | default(users_default_password) }}'
    home: '{{ item.home | default("/home/"+item.name) }}'
    createhome: '{{ item.createhome|default(users_create_homedirs) }}'
    system: '{{ item.system | default(omit) }}'
    append: yes
  with_items: "{{ users }}"
  when: >
    not ( item.name == ansible_ssh_user and
    item.state|default('present') == 'absent' )

- name: Add admin users to admin group
  user:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    groups: '{{ users_admin_group }}'
    append: yes
  with_items: "{{ users }}"
  when: >
    item.is_admin is defined and
    item.is_admin == true
