bin.includes = META-INF/,\
               plugin.xml,\
               .,\
               lib/,\
               LICENSE.txt,\
               CHANGELOG.md,\
               lib/LICENSE.txt,\
               lib/delta-kernel-api-4.1.0.jar,\
               lib/delta-kernel-defaults-4.1.0.jar,\
               lib/delta-storage-4.1.0.jar,\
               lib/jts-core-1.20.0.jar,\
               lib/parquet-column-1.17.0.jar,\
               lib/parquet-common-1.17.0.jar,\
               lib/parquet-encoding-1.17.0.jar,\
               lib/parquet-format-structures-1.17.0.jar,\
               lib/parquet-hadoop-1.17.0.jar,\
               lib/parquet-jackson-1.17.0.jar,\
               lib/RoaringBitmap-0.9.25.jar,\
               lib/shims-0.9.25.jar,\
               lib/unitycatalog-client-0.4.0.jar
source.. = src/
output.. = bin/
src.includes = LICENSE.txt
bin.excludes = lib/fetch_jars/
