- hosts: hadoop-hosts:&worker*
  tasks:
    - name: delete existing KNOSP plugins
      shell: rm -Rf /usr/local/lib/knime/plugins/com.knime.bigdata.spark1_6* /usr/local/lib/knime/plugins/com.knime.bigdata.spark.core* /usr/local/lib/knime/plugins/com.knime.bigdata.spark.node*
    - name: upload new plugins
      copy: src=/home/bjoern/tmp/empty/plugins/ dest=/tmp/upload-knosp-plugins/ owner=ec2-user group=ec2-user mode=ug=rw,o=r
    - name: move copied KNOSP plugins
      shell: mv /tmp/upload-knosp-plugins/* /usr/local/lib/knime/plugins/
